/**
 * Ambient Sounds Window
 * Separate window for ambient sound controls
 */

import { BrowserWindow, app, nativeImage } from 'electron';
import path from 'path';

// Webpack entry points (generated by Electron Forge)
declare const AMBIENT_SOUNDS_WEBPACK_ENTRY: string;
declare const AMBIENT_SOUNDS_PRELOAD_WEBPACK_ENTRY: string;

// Singleton instance
let ambientSoundsWindow: BrowserWindow | null = null;

export class AmbientSoundsWindowManager {
  /**
   * Open or focus the ambient sounds window
   */
  static open(): void {
    // If window already exists, focus it
    if (ambientSoundsWindow && !ambientSoundsWindow.isDestroyed()) {
      ambientSoundsWindow.focus();
      return;
    }

    // Create new window - use __dirname with relative path
    // Use PNG for Linux, ICO for Windows
    const iconFile = process.platform === 'win32' ? 'icon.ico' : 'icon.png';
    const iconPath = path.join(__dirname, '../../resources/icons', iconFile);
    const icon = nativeImage.createFromPath(iconPath);

    ambientSoundsWindow = new BrowserWindow({
      width: 650,
      height: 700,
      icon: icon,
      frame: false,
      transparent: true,
      resizable: false,
      show: false, // Don't show until ready
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
        sandbox: true,
        preload: AMBIENT_SOUNDS_PRELOAD_WEBPACK_ENTRY,
      },
    });

    // Load the ambient sounds renderer
    ambientSoundsWindow.loadURL(AMBIENT_SOUNDS_WEBPACK_ENTRY);

    // Show when ready
    ambientSoundsWindow.once('ready-to-show', () => {
      ambientSoundsWindow?.show();
    });

    // Clean up on close
    ambientSoundsWindow.on('closed', () => {
      ambientSoundsWindow = null;
    });

    // Open DevTools only in development (not in packaged app)
    if (!app.isPackaged) {
      ambientSoundsWindow.webContents.openDevTools({ mode: 'detach' });
    }
  }

  /**
   * Close the ambient sounds window
   */
  static close(): void {
    if (ambientSoundsWindow && !ambientSoundsWindow.isDestroyed()) {
      ambientSoundsWindow.close();
    }
  }

  /**
   * Check if window is open
   */
  static isOpen(): boolean {
    return ambientSoundsWindow !== null && !ambientSoundsWindow.isDestroyed();
  }

  /**
   * Get the window instance (for IPC communication)
   */
  static getWindow(): BrowserWindow | null {
    return ambientSoundsWindow;
  }
}
